version: '3'

services:
  # PostgreSQL Veritabanı
  postgres:
    image: postgres:15
    container_name: solar_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Solar API Uygulaması
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solar_api
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solar_db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: 